CREATE DATABASE IF NOT EXISTS crud_go;

USE crud_go;

CREATE TABLE IF NOT EXISTS users (
    ID INT AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted_at DATETIME,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS authors (
    ID INT AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted_at DATETIME,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS publishers (
    ID INT AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted_at DATETIME,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS categories (
    ID INT AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted_at DATETIME,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS books (
    ID INT AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    author_id INT NOT NULL,
    publisher_id INT NOT NULL,
    price INT,
    weight INT,
    published_at DATE,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted_at DATETIME,
    PRIMARY KEY (ID),
    FOREIGN KEY (author_id) REFERENCES authors(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (publisher_id) REFERENCES publishers(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS categorybooks (
    category_id INT,
    book_id INT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted_at DATETIME,
    PRIMARY KEY (category_id, book_id),
    FOREIGN KEY (category_id) REFERENCES categories(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (book_id) REFERENCES books(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT IGNORE INTO authors VALUES (1, 'Yudi Latif', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT IGNORE INTO authors VALUES (2, 'Rhenald Kasali', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);

INSERT IGNORE INTO publishers VALUES (1, 'Expose', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT IGNORE INTO publishers VALUES (2, 'Mizan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
